import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/components/AuthProvider";
import logo_white from "@/../public/logo_white.png";
import Image from "next/image";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${inter.className} antialiased `}
      >
        <Image 
          src={logo_white}
          alt="Logo"
          width={150}
          height={150}
          className="fixed top-4 left-4 z-50 shadow-lg shadow-slate-800 bg-slate-700 rounded-2xl"
          priority
        />
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
